### ISSUE TITLE
Rework troubleshooting docs

### ISSUE THREAD

**Issue by FloLey** [inmanta/inmanta-core#4965] opened 2022-10-10 07:45 UTC
While removing the docs of the dashboard, I noticed that the troubleshooting docs are written for the dashboard and not for the web-console. Those docs should be adapted.

**Comment by sanderr** [comment] 2022-10-10 07:49
Duplicate of #3652. I'll move that one up in the backlog.

**Closed by sanderr** 2022-10-10 07:49 UTC
