### ISSUE TITLE
Add admin user to the configuration

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta-core#5743] opened 2023-03-27 09:18 UTC
Currently any user is able to use the user list, add and remove APIs. The goal of this ticket is to introduce a the concept of an admin user in the configuration file. Any user listed there is an admin user and is able to use the APIs. Other users will get a 403.

Open question: Do we introduce an X-Inmanta-Admin: true header? This would allow the frontend to hide the user page. Alternatively we can also add it to the config.js of the frontend.

**Comment by arnaudsjs** [comment] 2023-03-27 09:35
This is a duplicate of #5644

**Comment by wouterdb** [comment] 2023-10-24 13:44
Why not add the admin status to the JWT?

**Comment by wouterdb** [comment] 2023-10-24 14:17
This ticket can wait until the FE is further along.

**Comment by sanderr** [comment] 2024-03-19 14:43
Overruled by #7394

**Closed by sanderr** 2024-03-19 14:43 UTC
Labels: discussion
