### ISSUE TITLE
improve performance of resource_logs

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta-core#6160] opened 2023-06-22 12:08 UTC
![image](https://github.com/inmanta/inmanta-core/assets/1788254/e8fab1a2-988c-4438-8084-032c496036b0)

it takes over 5 seconds on the mgmt orchestrator

**Comment by arnaudsjs** [comment] 2023-06-22 14:01
@wouterdb Isn't this a duplicate of #6147, for which we have a PR in the pipeline to fix it?

**Closed** 2023-06-22 14:10 UTC
